### ISSUE TITLE
Replace REST with GraphQL?

### ISSUE THREAD

**Issue by auguwu** [kashima-org/api#33]
Simple concept but very alien to people. GraphQL is a query DSL language that can be very powerful when used (like any other DSL). It filters out any data that you don't want from the API server.

We might make REST as an external option if people don't wanna use GraphQL. It's pretty simple when we get into it.

Let's say we make a POST request to `http://localhost:4456/graphql`:
We'll make a body as an object of `query` and `variables`

**query**: The query we can make to get the data
**variables**: Any variables that are required when we use the query.

```gql
{ getAccount($username: "") }
```

which the schema will be:

```gql
type AccountQuery {
  getAccount($username: String!)
}
```

**Comment by nowoel** [comment]
Update: I'll ask the dev team if they agree with this idea or we should keep both but use [fastify-graphql](https://npmjs.com/package/fastify-gql) as an endpoint and keep the REST API endpoints.

**Comment by ohlookitsderpy** [comment]
no lazy
